# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_convolutions.ipynb.

# %% auto 0
__all__ = ['conv']

# %% ../nbs/07_convolutions.ipynb 4
import torch
from torch import nn, tensor
from torch.functional import F

from pathlib import Path
import gzip, pickle

from torch.utils.data import default_collate
from typing import Mapping

from .training import Dataset, get_dls, fit, collate_device, def_device
from .datasets import show_images

# %% ../nbs/07_convolutions.ipynb 14
def conv(ni, nf, ks=3, stride=2, act=True):
    res = nn.Conv2d(ni, nf, stride=stride, kernel_size=ks, padding=ks//2)
    if act == True: res = nn.Sequential(res, nn.ReLU())
    return res
